### PR TITLE
Add a Docker image

### PR DESCRIPTION
**Pull request by seeflanigan**
Adds `Dockerfile` which builds into an image where `rake` runs tests (which pass, at the time of this writing).

### CODE REVIEW

**Comment by searls** [comment]
Hey Cory, since I don't know how to Docker at all, I have a couple questions:

1. Is there a way for us to assert the dockerfile works in the build (to test it?)

2. Is it typical for a rubygem to include a dockerfile? What does it accomplish?

**Comment by seeflanigan** [comment]
Hi Justin, 

Thanks for bringing quality inquiries! I'll do my best to address them accordingly.

1. There almost certainly is. I don't yet know if an idiom for verifying correctness of Docker containers has emerged, yet. That said, since a container is something of a proxy around running commands, there's almost certainly a way. First MVV (minimum viable verification) to mind is something as simple as a `bash` script. Do you have specific acceptance criteria in mind for what will constitute a valid test?

2. Initial thought is without further survey of rubygem repos, I cannot confidently assert whether this is typical, yet. However, the primary accomplishment and value-add from my perspective is the reduction of dependencies for bootstrapping a development environment to one; Docker. Also, by virtue of ensuring the Dockerfile successfully builds and runs the application, it provides a versioned source of programmatic documentation about host-level application dependencies and build steps. Because the Docker DSL is minimal, and mostly an abstraction around the (`bash`) CLI, I think it reduces the language-specific barrier of entry for bootstrapping a development environment, and running tests. 

Another benefit is it provides this value unobtrusively. If you have Docker installed, great! It's a one-step (`docker build`) process to set up a working environment. If not, that's fine too, the `Dockerfile` is inert without Docker, and doesn't prohibit anyone from building the traditional multi-step way directly on `localhost` (eg `install rvm`, `install a ruby`, `bundle install`...).

Simply stated, it provides me a much faster path to running `rake` and seeing tests pass, and meanwhile leaves you with freedom of choice over your development workflow.

Provided we can agree on testing requirements, are you interested in merging a `Dockerfile`, or would you prefer that I add it to `.gitignore` for now?

**Comment by searls** [comment]
I'm currently inclined to ask we .gitignore this for modules/libs/gems, which should be as permissive and heterogenous as possible because we don't control the context in which they run (the "don't commit Gemfile.lock" argument applies).

The worry being that with a team working on a Gem and all using the same Dockerfile, it could encourage one of two things:

1. More homogeneous dev environments can lead to blind spots of environments and contexts from which other people run the gem. Something as simple as setting an env var that affects how Ruby manages memory could result in bugs that are hard for any contributor using docker to reproduce or debug.

2. Everything starts simple, both the lib itself and the Dockerfile. In the event something is painful in the future, the Dockerfile would give us a second place to soothe that pain. Using the same example, an env var that gives us more memory headroom by our runtime could reduce the frequency of an issue for us as contributors, but unintentionally reduce the urgency of addressing whatever the root cause is, which is likely causing the same pain for countless more users.

None of the above is really that big of a deal if all the devs & deployed environments are under your control, which is why I think the "lib vs app" split on whether to commit a Dockerfile applies.

**Comment by searls** [comment]
Some toots:

* https://twitter.com/MikeKusold/status/778058825542676480 

* https://twitter.com/dkubb/status/778040931605815296 - might be compelling if you have a REALLY onerous setup, but Suture should really be able to be run on any Ruby version, so `bundle && be rake` should just work for virtually any ruby environment

* https://twitter.com/sosedoff/status/778036755354165248

**Comment by searls** [comment]
So I vote changing this to a .gitignore and merging that but keeping the Dockerfile in the repo's history for posterity

**Comment by seeflanigan** [comment]
@searls: did it!

**Pull request merged**
